<?php
$lang = array(

// Necessário para a página MÓDULOS

'flag_master_module_name'		=> 'Flag Master',
'flag_master_module_description'	=> 'Permite que visitantes marquem registros e informem aos administradores conteúdo especial ou inapropriado.',

//----------------------------------------
'dashboard' => 'Mural',
'profiles' => 'Perfis',
'profile' => 'Perfil',
'profiles_instructions' => 'Flag Master permite que você crie múltiplas coleções ou "Perfis", para melhor customizar suas necessidades. Abaxiso estão os perfis existentes.',
'no_profiles' => 'Nenhum Perfil Localizado',
'add_profile' => 'Adicionar Perfil',
'view_profile' => 'Ver Perfil',
'edit_profile' => 'Editar Perfil',
'profile_not_found' => 'Perfil Não-Localizado',	
'back_to_profile' => 'Voltar ao Perfil',	
'profile_updated' => 'Perfil Atualizado',
'profile_not_updated' => 'O perfil não pode ser atualizado',
'delete_profiles_confirm' => 'Tem certeza que deseja excluir estes perfis?',
'profiles_deleted' => 'Perfis Excluídos',
'profile_options_deleted' => 'Opção (ões) de perfil Excluída(os)',
'profiles_delete_failure' => 'O(s) Perfil(s) não puderam ser excluídos',
'profile_id_required' => 'profile_id é obrigatório!',
'invalid_profile_id' => 'profile_id inválido',
'notify_emails' => 'E-mails de aviso',
'profile_added' => 'Perfil Adicionado',
'no_flagged_comments' => 'Nenhum Comentário Marcado',
'no_flagged_entries' => 'Nenhum Comentário Marcado',
'no_entry_flags' => 'Nenhum Registro Marcado',
'first_flag' => 'Primeira Marcação',
'last_flag' => 'Última Marcação',
'no_flag_options' => 'Nenhuma Opção de Marcação',
'add_option' => 'Adicionar Opção',
'option_added' => 'Opção Adicionada',	
'view_option' => 'Ver Opção',
'no_options' => 'Nenhuma Opção Localizada',	
'edit_option' => 'Editar Opção',	
'add_child_option' => 'Adicionar Opção Dependente',
'no_child_options' => 'Nenhuma Opção Dependente',
'back_to_option' => 'Voltar à Opção',
'user_defined' => 'Definido pelo Usuário',
'delete_options_confirm' => 'Tem certeza que você deseja excluir estas opções?',
'delete_flags_confirm' => 'Tem certeza que você deseja excluir estas marcações?',
'member_only' => 'Apenas Membro',
'user_defined_instructions' => 'Se marcado, uma area de texto será mostrada para permitir que usuários insiram suas próprias opiniões.',
'member_only_instructions' => 'Se marcado esta opção ser mostrada apenas para usuários logados no site.',
'description_instructions' => 'Dados opcionais sobre esta opção.',
'title_instructions' => 'O texto para mostrar próximo à opção do campo do formulário.',
'view_entry_flags' => 'Ver Marcações de Registro',
'entry_title' => 'Título do registro',
'option_title' => 'Título da Opção',
'no_flags' => 'Sem Marcações',				
'delete_selected' => 'Excluir Seleção',
'total_flags' => 'Total de Marcações',
'active' => 'Ativo',
'inactive' => 'Inativo',
'created_date' => 'Data de Criação',
'user_name' => 'Usuário',		
'entry' => 'Registro',
'comment' => 'Comentário',	
'global_config' => 'Configuração Geral',
'flag_master_date_format' => 'Formato da Data',
'flag_master_date_format_instructions' => 'O formato da data que você deseja que o Flag Master utilize para manipular as datas. Note que o formato deve estar em conformidade com o <a href="http://expressionengine.com/user_guide/templates/date_variable_formatting.html#date-formatting-codes" target="_blank">formato de datas do ExpressionEngine</a>.',
'type' => 'Tipo',
'flags_deleted' => 'Marcações Excluídas',
'back_to_entry' => 'Voltar para o Registro',
'name_instructions' => 'Como você deseja denominar este Perfil?',
'status_instructions' => 'Se um perfil não estiver ativo, ele não estará disponível através das tags do módulo.',
'type_instructions' => 'Qual o tipo de conteúdo que esta marcação de perfil será utilizada? A precisão é MUITO importante aqui para verificar suas configurações.',
'notify_emails_instructions' => 'Quem você deseja avisar quando o Flag Master fizer algo? Insira 1 endereço de e-mail por linha.',
'view_comment_flags' => 'Ver Marcações de Comentários',
'back_to_dashboard' => 'Voltar para o Mural',
'back_to_comment' => 'Voltar para Comentários',
'platform' => 'Plataforma',
'comment_not_found' => 'Comentário Não Localizado',
'auto_close_threshold' => 'Auto-Encerrar Assunto',
'auto_close_threshold_instructions' => 'Quantas marcações são necessárias antes que este item seja encerrado automaticamente. Deixe em branco ou insira  0 para desativá-lo.',
'entry_status_change_notification_subject' => 'Alterar Status do Registro',
'comment_status_change_notification_subject' => 'Alterar Status do Comentário',	
'comment_status_change_notification_message' => '
Olá,

Um comentário no seu site obteve o status de ENCERRADO devido ao Flag Master. Você pode visualizar seu comentário encerrado abaixo:
{view_url}
		
Flag Master :)
		',
		

'flag_type' => 'Tipo da Marcação',
'flag_type_instructions' => 'Quais tipos de marcações você deseja mostrar?',
'view_entry_comment_flags' => 'Comentários e Registros Marcados',
'settings' => 'Configurações',
'no_flags_found' => 'Nenhuma Marcação Localizada',
'title' => 'Título',
''=>''
);